### ISSUE TITLE
Checksum error during "Fetch the Rocket.Chat binary tarball"

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat.Ansible#10]
While running the RocketChat Ansible installation, I get the following error:

```
{"changed": false, "failed": true, "msg": "The checksum for /var/lib/rocket.chat/rocket.chat-latest.tgz did not match c761d354094e4ce5c5ebef786dd023688111042290f2c26f1e93ba3b9c6ee8b8; it was e6caca890c86f79595da14398dd3ab0c0d3222932d6a8a1b38c6e5082531acd2."}

```

**Comment by cmacrae** [comment]
The new defaults have now been updated to use the latest hash sum.  
Please update the role to the latest (`ansible-galaxy install -f -r path/to/requirements.yml`, if you're using Ansible Galaxy).
