### ISSUE TITLE
Ubuntu 14 upstart service lacks permission to write to pid-file 

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat.Ansible#11]
On a fresh installation, via the Ansible option, we get a 502 Bad Gateway error from nginx. The Ansible script reports that all steps were successful:

```
ok=34   changed=0    unreachable=0    failed=0  
```
How can we make sure the Rocket.Chat instance is running for the nginx proxy?

**Comment by cmacrae** [comment]
Please try to provide more information regarding the system you're running.

- Ensure the `rocketchat` service is running
- Check the Nginx access/error logs for any significant messages
- Ensure all role variables pertaining to the URL by which you access the site have been set correctly

**Comment by brylie** [comment]
OK, thanks. I will follow up tomorrow at work.

**Comment by cmacrae** [comment]
:+1:

**Comment by nikksno** [comment]
Hi! I had the same problem the other day on my Ubuntu 14 VM and was about to open an issue myself. RC was actually working until I first rebooted. Then after reboot it wasn't. The RC service was not running. I tried `sudo service rocketchat start` but although the feedback from the command was normal it didn't actually start. From the log [`cat /var/log/rocketchat.log`] I got:
```
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/var/run/rocketchat.pid'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at writePid (/usr/local/lib/node_modules/forever/bin/monitor:13:6)
    at null.<anonymous> (/usr/local/lib/node_modules/forever/bin/monitor:46:5)
    at EventEmitter.emit (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at /usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:175:10
    at process._tickCallback (node.js:448:13)
```
So after some searching but no findings I randomly tried manually creating a rocketchat.pid file:
`sudo touch /var/run/rocketchat.pid`
And setting it to be owned by the rocketchat user - no idea if this is correct:
`sudo chown rocketchat:rocketchat /var/run/rocketchat.pid`
After that if I tried a `service rocketchat start` it all worked. I have to do this after every reboot.
Any ideas as to why? Is this a correct workaround?

I've included all commands for others to try if they find themselves in my same situation.

Thanks!

**Comment by cmacrae** [comment]
Hey @nikksno - thanks for joining in. Ah! Oh dear, alright, thanks for the details - that's something I'll have to look into. Yes, that sounds like a good fix, I'll just need to implement the creation of this file in the init script :+1:

I'll get onto this when I can (hopefully this evening).

**Comment by nikksno** [comment]
Ok good work there happy to help :)
