### ISSUE TITLE
Checksum did not match

### ISSUE THREAD

**Issue by max-b** [RocketChat/Rocket.Chat.Ansible#12]
```
TASK [RocketChat.Server : Fetch the Rocket.Chat binary tarball] ****************
fatal: [chat1]: FAILED! => {"changed": false, "failed": true, "msg": "The checksum for /var/lib/rocket.chat/rocket.chat-latest.tgz did not match e6caca890c86f79595da14398dd3ab0c0d3222932d6a8a1b38c6e5082531acd2; it was 21ef5ee220671e5f514f240d1423514c5780d81d6ffba8720d19660079099925."}
```

It was easy enough to change the `rocket_chat_tarball_sha256sum` variable in my inventory, but I just thought you all would want to know that the default no longer matches.

**Comment by cmacrae** [comment]
Thanks @max-b - yeah, this is a manual process I have to keep up with at the moment.  
I'll put an FAQ up, or something in the README.

**Comment by max-b** [comment]
Nice - thanks a bunch :)

**Comment by cmacrae** [comment]
No problem at all, thanks for taking the time to bring this to my attention :+1:
