### ISSUE TITLE
ERROR! failed to combine variables, expected dicts

### ISSUE THREAD

**Issue by BackIsBachus** [RocketChat/Rocket.Chat.Ansible#13]
Hello,

I'm trying to run this role on Debian 8 (I already tried it on Ubuntu 15.04 and it worked) with Ansible 2.1.0 and I am using the v2.0 of this role.
During the installation of MongoDB (I think) I get the following error:

```
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode':
"deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main"
"deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main"
```

The role I execute is:
```
- hosts: local
  vars:
    rocket_chat_automatic_upgrades: True
  roles:
    - RocketChat.Server
```

Thanks!

**Comment by cmacrae** [comment]
Hi @BackIsBachus - hmm, okay. I haven't tested with 2.1.0, and don't currently support it, as it hasn't been released. However, as far as I know, it should just work.

I'll try and get around to some testing today.

**Comment by BackIsBachus** [comment]
I'll try to test it with 2.0 and come back to you as well.

**Comment by cmacrae** [comment]
@BackIsBachus Any luck testing?

**Comment by BackIsBachus** [comment]
Yeah (sorry I forgot to report it back here ^^), I don't have thoses errors when I switch to the stable-2.0.0 branch of Ansible, But I have a bunch of other errors (that I forgot to copy-paste so I'll get right back at testing).
That's really weird because I already did an install that went smoothly on Ubuntuu 15.04, but I still can't make it work on Debian 8.

**Comment by cmacrae** [comment]
@BackIsBachus No problem! Hmm, okay - I suspect the above issue mentioned is introduced by Ansible 2.1, which isn't supported at the moment.

Though... that's very strange regarding Debian 8 - I do vagrant tests often and haven't run into any failures on fresh Debian 8 systems. Have you ensured you've got the latest code?

**Comment by cmacrae** [comment]
Closing, as I haven't encountered this in any of my continuous tests

**Comment by chanux** [comment]
JFTR, I faced this issue with Ansible 2.2.0 when I tried to load variables from Ansible Vault where I used `foo=bar` instead of `foo: bar`. Newer versions helpfully error out.

ansible/ansible#14678
