### ISSUE TITLE
Not deleting tarball prevent from updating

### ISSUE THREAD

**Issue by BackIsBachus** [RocketChat/Rocket.Chat.Ansible#20]
Hey,

I stumbled across a weird situation while trying to update from 0.26.0 to 0.27.0 and to 0.28.0: the role did not download the latest tarball because `rocket.chat-latest.tgz` was already present in the Rocket.Chat install directory (`/var/lib/rocket.chat/` by default here in my situation).

So since the latest tarball was not download the role only reapplied the last update it downloaded (0.26.0 in my case).

Manually deleting this archive solved this problem.

I may do a pull request later today or this weekend if is not just an issue on my side (and manage to understand how Ansible and pull requests work).

**Setup:**
Ubuntu 15.10 with Ansible running on the same host as the Rocket.Chat instance.

**Comment by cmacrae** [comment]
Did you update the `rocket_chat_tarball_sha256sum` to reflect the associated hashsums?
The way this process works is, Ansible fetches the tarball for whichever version you're using, then does a comparison of the hash sums to see if it has changed. If it does change (so, after an updated tarball is released) and you have the correct hash sum defined, that triggers the upgrade process.

The upgrade process removes some data which is used in a conditional for the unarchiving task.

**Comment by BackIsBachus** [comment]
I didn't update the `rocket_chat_tarball_sha256sum` before running the update because I don't know where to find the hash before trying to install it (except by downloading the tarball manually and hashing it myself).

So for my setup I had the hash of the 0.26.0 in the `rocket_chat_tarball_sha256sum` but I was tracking the version `latest` (by using the default value or manually adding it) and inside `/var/lib/rocket.chat` I had the `rocketchat-latest.tgz` tarball of the 0.26.0 release. And the process ran normally without error.

So from what you are saying this is actually the expected behavior ?

**Comment by cmacrae** [comment]
The intention of using `latest` as your `rocket_chat_version` is that you will track the latest releases of Rocket.Chat.
It works like so:
- The team release a new version available at the `latest` link (https://rocket.chat/releases/latest/download)
- When running this role, Ansible will look at the `rocket.chat-latest.tgz` it has on the filesystem and compare its hash sum with `rocket_chat_tarball_sha256sum`. If the hash sum matches, nothing is done. If the hashsum doesn't match, it will go and fetch the `latest` tarball.
- Fetching the `latest` tarball triggers the upgrade tasks, if they are enabled through `rocket_chat_automatic_upgrades`
- The upgrade tasks simply back up your current install (if you've elected for such behavior), then remove the `bundle` directory extracted from the previous tarball
- The absence of the `bundle` directory triggers an unarchive of the `rocket.chat-latest.tgz` tarball on the filesystem.

Hopefully that's a little more clear. You should either track specific releases, `latest` or `develop`, using the associated hash sums. The releases can be found here: https://rocket.chat/releases

To answer your question regarding hash sums, yes, this is something you will have to get yourself - quite easy to script out. Either that, or follow `latest` and wait for the role's defaults to get updated by me, then re-fetch the role using `ansible-galaxy`, but that's not a very convenient method, as I can't track the latest hash sums as quickly as they're released :)

**Comment by cmacrae** [comment]
Probably worth mentioning that althought I've used `latest` as an example above, it works the same for upgrading via specific versions, or from specific versions to `latest`.

You could have the following set-up:
``` yaml
rocket_chat_version: 0.27.0
rocket_chat_tarbal_sha256sum: <0.27.0's hashum here>
```

And then upgrade to 0.28.0 by simply changing them to:
``` yaml
rocket_chat_version: 0.28.0
rocket_chat_tarbal_sha256sum: <0.28.0's hashum here>
```

Or jump up to `latest:
``` yaml
rocket_chat_version: latest
rocket_chat_tarbal_sha256sum: <latest's hashum here>
```

**Comment by BackIsBachus** [comment]
Thank you for the detailed answer. I will script the hash part from now on!

**Comment by cmacrae** [comment]
You're welcome 🙂 Don't hesitate to ask any further questions if need be!
