### ISSUE TITLE
ERROR: file could not read: [...]upgrade.yml

### ISSUE THREAD

**Issue by infinitnet** [RocketChat/Rocket.Chat.Ansible#3]
It seems like upgrade.yml is referenced in `./roles/RocketChat.Server/main.yml` via `include` but the file is missing from the playbook. This results in:

```
ERROR: file could not read: /root/ansible/roles/RocketChat.Server/handlers/upgrade.yml
```

**Comment by cmacrae** [comment]
Have you modified any of the code at all?  
This is a feature that is currently disabled by commenting it out, as you'll see [here on line 92 of `main.yml`](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/tasks/main.yml#L92).

I'm awaiting the official release of Ansible 2.0, after which this will be enabled.

As far as I can tell, there should be no instance in which Ansible attempts to actually include `upgrade.yml` with the current code.

**Comment by infinitnet** [comment]
Thanks for your response. I'm using 1.9.4 from EPEL and no, I didn't modify any of the code, just had galaxy pull it. You can see the reference to the missing file here in this github repo as well (https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/handlers/main.yml#L10 to be specific). I did comment out that `include`, however I don't seem to have much luck as I'm running into more issues now which I opened another bug report about.

**Comment by cmacrae** [comment]
No problem :+1: 

I'm not sure what you mean by "missing file", `upgrade.yml` is certainly there:
https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/tasks/upgrade.yml

I'm really not sure what could be causing this, I'm afraid, but - let me try to replicate this

**Comment by infinitnet** [comment]
You're getting the path wrong. ./tasks/upgrade.yml might be there, but the file that's called by the include in main.yml is ./handlers/upgrade.yml and that file is missing. :wink:

**Comment by cmacrae** [comment]
No, I'm not getting the path wrong - `upgrade.yml` is what gets included, this has been thoroughly tested.

**Comment by infinitnet** [comment]
In line 10 in this file (https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/handlers/main.yml#L10) you include upgrade.yml from the same directory, which is `handlers`, not `tasks` (the latter has the upgrade.yml file in it, the former doesn't). Not sure how else to explain this. You can replicate it by just following the steps one by one on a CentOS 7 system: https://github.com/RocketChat/Rocket.Chat/wiki/Easy,-hands-off-deployment-with-Ansible

**Comment by cmacrae** [comment]
I understand exactly what you're saying, and I'm telling you: even when using `include: upgrade.yml` in `handlers/main.yml`, `tasks/upgrade.yml` is what is included. Like I said: this has been thoroughly tested.  

I'm testing now with Ansible 1.9.4 to see if this is where the problem has been introduced.

**Comment by cmacrae** [comment]
Yep, looks like it's simply differing Ansible versions.
The assessment of `include` paths must have been changed when they fixed the bug in 2.0:
```
ERROR: file could not read: ansible/roles/external/RocketChat.Server/handlers/upgrade.yml
```

Thank you for bringing this to my attention :+1: I'll update you once this has been fixed.

**Comment by infinitnet** [comment]
Alright I see, not sure what causes this then. If you test this on CentOS 7 just following the steps from the wiki documentation I mentioned in my last response, I'm pretty sure you should be able to replicate this, because I didn't modify anything and am using a fresh and minimal EL7.

PS: Ok you were faster than me. :) Thanks for the extraordinary fast support by the way.

**Comment by cmacrae** [comment]
You're very welcome :) Thank you for raising this issue! I've been blissfully operating on Ansible release candidates... so, it's good someone gave me a poke about this.  

I've already found that creating a "dummy" `handlers/upgrade.yml` file will circumvent this problem - but I want to address the other issues present with this role on 1.9.4 before closing this off.

**Comment by cmacrae** [comment]
Right, I've just pushed the fixes. Wanna grab the latest copy and give it a try?

**Comment by infinitnet** [comment]
Yeah, seems to be doing its work now and the other issue is gone as well. Thanks a lot for taking care of this so quickly! I sent you a small contribution via email as a thank you. Have a nice evening, I'm closing this.

**Comment by cmacrae** [comment]
Great, glad to hear it's working! No problem at all - my thanks to you, also; as I wouldn't have come across this :)

Nice one, I'll check it out now
