### ISSUE TITLE
Up coming Rocket.Chat node.js version upgrade.

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Ansible#33]
0.40.0 will be landing soon, and with it will come a dependency shift from Node.js 0.10.4x to Node.js 4.5

**Comment by xenithorb** [comment]
Thanks for the heads up!

**Comment by geekgonecrazy** [comment]
@xenithorb sure thing!  Hit me as I was prepping documentation upgrades.  Let me know if you need anything to assist with this

**Comment by rwarsing** [comment]
Upgraded to v40 & rocketchat failed to start.  Upgraded node to v4.5.0 - didn't fix.  Anything else to try?

**Comment by rwarsing** [comment]
Bandaid, install node 4.5, change the below variable & re-run.
1.) sudo n 4.5
2.) rocket_chat_node_10_40_path: /usr/local/n/versions/node/4.5.0/bin

**Comment by xenithorb** [comment]
Yes, I'm working on this now. Will close the ticket when complete.
