### ISSUE TITLE
Incorrect checksum in defaults/main.yml

### ISSUE THREAD

**Issue by OtherSystems** [RocketChat/Rocket.Chat.Ansible#37]
In [defaults/main.yml](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/defaults/main.yml) the ansible role defaults to the latest version and checks a checksum, this checksum however is not correct for the latest version of rocket chat. 

Running debian jessie and ansible 2.2.1.0-1

**Comment by cmacrae** [comment]
See: https://github.com/RocketChat/Rocket.Chat.Ansible#faq in the README

**Comment by OtherSystems** [comment]
Ah missed that, where can I get the latest checksum?

**Comment by cmacrae** [comment]
You can grab the download here: https://rocket.chat/download (probably interested in the links at the bottom), then use the `sha` command, using the 256 algorithm arg, to get the hash :)
