### ISSUE TITLE
Introduce new rocket_chat_mongodb_ vars to make role more generic

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat.Ansible#40]
Hi folks,

I was wondering: currently it doesn't seem to be possible to define the user / password for the connection to mongodb. It is also not possible to say that one wants to connect to rocket.chat via TLS and furthermore it's not possible to disable the oplog if one does not use it.

I would therefore want to introduce the following new vars:

* STRING rocket_chat_mongodb_user
* STRING rocket_chat_mongodb_password
* BOOL rocket_chat_mongodb_connect_tls

This would result in a MONGO_URL like this:

    MONGO_URL=mongodb://{{ rocket_chat_mongodb_user }}:{{ rocket_chat_mongodb_password }}@{{ rocket_chat_mongodb_server }}:{{ rocket_chat_mongodb_port }}/rocketchat?ssl={{ rocket_chat_mongodb_connect_tls }}

* BOOL rocket_chat_mongodb_use_oplog

This would either define or not define MONGO_OPLOG_URL in the files:

* templates/rocketchat_upstart.j2
* templates/rocketchat.service.j2

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Any feedback on this or anything I can clarify? :)

Cheers
Thomas

**Comment by xenithorb** [comment]
Would you be willing to implement this on the `develop` branch?

**Comment by TwizzyDizzy** [comment]
The reason I haven't done that already is, that currently I have the feeling that I'm not good enough with ansible yet. But I'll have a look at it in time and give it a shot...

Cheers
Thomas
