### ISSUE TITLE
selinux and nginx issue on centos 7

### ISSUE THREAD

**Issue by taybin** [RocketChat/Rocket.Chat.Ansible#5]
On Centos7, I had to run these commands for nginx to successfully proxy to port 3000

sudo cat /var/log/audit/audit.log | grep nginx | grep denied | sudo audit2allow -M mynginx
sudo semodule -i mynginx.pp

I learned this from http://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

It'd be nice to add this to the ansible configuration.

**Comment by cmacrae** [comment]
Hey @taybin - thanks for raising this.
I'm afraid I consider this an edge case and would like to keep such steps outside of this Ansible role.

The nginx component of this role is intended as a simplistic, minimal implementation for ease of access.
If finer grained control of nginx, or surrounding software that may impact its ability to function is required, one can opt to not include nginx via the `rocketchat_include_nginx` variable, and it its place use a different role/set of roles.

That said, this is also something that could be very easily addressed in a playbook using a `pre_task` :+1:

**Comment by geekgonecrazy** [comment]
@cmacrae I'm not super familiar with ansible.  Is this something that could be optionally specified and they would have to intentionally invoke?

Or maybe we could just include this as a note in the documentation around the ansible playbook.  That might be better.

**Comment by cmacrae** [comment]
@geekgonecrazy Yeah, possibly. Could add it to the documentation I suppose. The thing is, this is just more specific to nginx, is all, and this isn't an nginx role.

**Comment by taybin** [comment]
I understand not wanting to add it to the script, but the docs make the current ansible installer sound very hands off.  I was very confused for a while about why my setup just wasn't working.  Maybe a mention in a FAQ or troubleshooting section?

**Comment by cmacrae** [comment]
@taybin Yep, I definitely agree - I'll review this today at some point and add it to the documentation. As such, I'm re-opening this issue and will resolve it once it's been added.

**Comment by cmacrae** [comment]
@taybin There ya go :) 1a7788d should fix this - wanna give it a try?

**Comment by taybin** [comment]
Works for me, and is shorter and sweeter than the audit2allow hack above.  Thanks!

**Comment by cmacrae** [comment]
No problem :) Glad it's working
