### ISSUE TITLE
Implement GPG verification in place of sha256 hashes

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat.Ansible#50]
https://github.com/RocketChat/Rocket.Chat.Ansible/issues/44#issuecomment-338241507

We automatically generate GPG `.asc`s now, that we can use to verify the builds instead of me updating the hash on the role here periodically as the "correct" hash.

We should: 

1. Ensure that people still have the ability to check SHA256 sums should they want to retain that workflow. This should be easily accomplished by turning off the verification check with the option I included last year to turn off checking.

2. Import RC's official public key properly so that subsequent checks are verified against the "known good" key. @geekgonecrazy  - could use your help with sourcing the correct GPG key which I will include in this role. 

3. Include the GPG key in the role

3. Download the builds, and verify the tarballs.

**Comment by geekgonecrazy** [comment]
@xenithorb https://github.com/RocketChat/Docker.Base.Image/blob/master/Dockerfile#L6
