### ISSUE TITLE
upgrade task needs to restart the rocketchat service

### ISSUE THREAD

**Issue by taybin** [RocketChat/Rocket.Chat.Ansible#7]
I had to login and manually restart the service or it continued to serve the old website.

**Comment by cmacrae** [comment]
Hey @taybin, thanks for bringing this to my attention :) I'll have this fixed shortly, in fact I've written the code already, just gotta do some testing.

**Comment by cmacrae** [comment]
@taybin: Well, that fixes it :+1: Thanks for this!
