### ISSUE TITLE
Installation behind corporate proxy

### ISSUE THREAD

**Issue by nikksno** [RocketChat/Rocket.Chat.Ansible#8]
The `rocket_chat_mongodb_keyserver` variable specified in `RocketChat.Server/defaults/main.yml` is:
`keyserver.ubuntu.com`
However this causes the installation to fail if a proxy is blocking outbound traffic on certain ports. A working solution is to change the var to:
`hkp://keyserver.ubuntu.com:80`
I can't say for sure this is the best solution but it definitely works.
Thanks for looking into this!

**Comment by cmacrae** [comment]
Hey @nikksno, thanks for raising this.  

Okay, cool - I can take a look at setting this as the default, makes sense really - if it works in both cases (behind a proxy/not behind a proxy).  

I can't imagine why it would, but if this introduces problems with the standard deployment (not behind a proxy), this can easily be overridden, either in the playbook or inventory :+1: 

I'll test it out in a few minutes and let you know how it goes.

**Comment by nikksno** [comment]
Nice thanks! First issue ever opened I'm glad it makes sense :)

**Comment by cmacrae** [comment]
Yep, all looks well - this has been updated in 4df249d, thanks! :)

**Comment by nikksno** [comment]
Awesome thank you!

**Comment by cmacrae** [comment]
No problem @nikksno, thanks again for the contribution - if you have any others, please don't hesitate to let me know!
