### ISSUE TITLE
sha256sum incorrect

### ISSUE THREAD

**Issue by nikksno** [RocketChat/Rocket.Chat.Ansible#9]
I'm not sure if I did anything wrong but upon installation the sha256sum verification fails as the file's checksum is different than the one specified in the var `rocket_chat_tarball_sha256sum` inside `RocketChat.Server/defaults/main.yml`. This is the error message:

```The checksum for /var/lib/rocket.chat/rocket.chat-latest.tgz did not match 99415e9c7304444dc35895623e58efa066ec83ab9d2b85aec0d50c78413c5252; it was 55c61b05c1f0bd3190328a721da303bc75b8fb313f7de4c54a77cae37ff6760b.```

Downloading the file elsewhere and correcting the value of the var solves the problem.
How does the defaults file keep the checksum up to date between new RC releases? Is the value hard coded inside the var?

Thanks!

**Comment by cmacrae** [comment]
Hi again @nikksno :wave: 

Yep, it's a hardcoded value - I have to manually update it between releases, then users either have to pull down the latest code (`ansible-galaxy install -f -r path/to/requirements.yml`) or override the default value in their playbook/inventory.

The latest has been updated to the hash sum above (`55c61b05c1f0bd3190328a721da303bc75b8fb313f7de4c54a77cae37ff6760b`), so if you pull the latest version of the role down, it should work just fine.

This is less than ideal, really - I do plan on putting an automated process in place for this in the near future.

**Comment by nikksno** [comment]
Ok perfect thanks for the confirmation!
